=head1 NAME

HTML::Mason::Commands - Mason command reference

=head1 DESCRIPTION

This was the documentation for the C<mc_> command set. In Mason 0.8 and
beyond, C<mc_> commands have been replaced by the new B<L<HTML::Mason::Request>> API. e.g.

   mc_comp becomes $m->comp
   mc_file becomes $m->file
   etc.

Below is a description of how to convert your C<mc_> commands to C<$m>
methods. There is also a utility provided with the distribution,
F<bin/convert0.8.pl>, that performs these conversions for you.
For backwards compatibility C<mc_> commands still work for a
limited time but will eventually go away.

=over

=item

C<mc_abort> becomes C<$m-E<gt>abort>

=item

C<mc_auto_comp> becomes C<$m-E<gt>fetch_next-E<gt>path>

=item

C<mc_auto_next> becomes C<$m-E<gt>call_next>

=item

C<mc_cache> becomes C<$m-E<gt>cache>

=item

C<mc_cache_self> becomes C<$m-E<gt>cache_self>

=item

C<mc_caller> becomes C<$m-E<gt>callers(1)-E<gt>path>

=item

C<mc_call_self> becomes C<$m-E<gt>call_self>

=item

C<mc_comp> becomes C<$m-E<gt>comp>

=item

C<mc_comp_exists> becomes C<$m-E<gt>comp_exists>

=item

C<mc_comp_source()> becomes C<$m-E<gt>current_comp-E<gt>source_file>

=item

C<mc_comp_source(path)> becomes C<$m-E<gt>fetch_comp(path)-E<gt>source_file>

=item

C<mc_comp_stack> becomes C<map($_-E<gt>title,$m-E<gt>callers)>

=item

C<mc_date> goes away, this was a legacy function. Replace by calling
the date formatting function of your choice on C<$m-E<gt>time>.

=item

C<mc_dhandler_arg> becomes C<$m-E<gt>dhandler_arg>

=item

C<mc_file> becomes C<$m-E<gt>file>

=item

C<mc_file_root> becomes C<$m-E<gt>file_root>

=item

C<mc_out> becomes C<$m-E<gt>out>

=item

C<mc_time> becomes C<$m-E<gt>time>

=item

C<mc_suppress_http_header> (with or without argument) no longer has
any effect and can simply be removed. See L<Devel/Sending HTTP
Headers> for more information.

=back

=head1 AUTHOR

Jonathan Swartz, swartz@transbay.net

=head1 SEE ALSO

L<HTML::Mason>,
L<HTML::Mason::Devel>

=cut
