=head1 NAME

Components.pod - Former Developer's Guide

=head1 DESCRIPTION

The HTML::Mason::Component class reference is in L<HTML::Mason::Component>.

The Component Developer's Guide is now in L<HTML::Mason::Devel>.

=head1 AUTHOR

Jonathan Swartz, swartz@transbay.net

=head1 SEE ALSO

L<HTML::Mason>,
L<HTML::Mason::Commands>

=cut
